version: '3'
services:
# BACK END
  api:
    container_name: api
    build:
      context: ./api/docker/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
      - ./api/php.ini:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    tty: true

  mysql:
    container_name: mysql
    image: mysql:8.0.3
    build:
      context: ./api/docker/mysql
      dockerfile: Dockerfile
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:80"
    volumes:
      - ./api/my.cnf:/etc/mysql/conf.d/mycnf
      - ./api/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      TZ: "Asia/Tokyo"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: test
      PMA_PASSWORD: test
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./api/phpmyadmin/sessions:/sessions
    container_name: phpmyadmin
  
  # FRONT END
  client:
    build:
      context: client
      dockerfile: Dockerfile
    
    # command: "yarn dev"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    tty: true